version: '3'
services:
  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=blog
      - MONGO_INITDB_ROOT_PASSWORD=123456
  blog_node:
    build: .
    command: 'npm start'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_SERVICE_NAME=mongo_db
    depends_on:
      - mongo_db
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
